- name: "AUTOMATED | 1.1.1.3 | Ensure mounting of udf filesystems is disabled"
  block:
    - name: "AUTOMATED | 1.1.1.3 | Ensure mounting of udf filesystems is disabled | Edit modprobe config"
      lineinfile:
        dest: /etc/modprobe.d/udf.conf
        regexp: "^(#)?install udf(\\s|$)"
        line: install udf /bin/true
        create: yes

    - name: "AUTOMATED | 1.1.1.3 | Ensure mounting of udf filesystems is disabled | Disable udf"
      modprobe:
        name: udf
        state: absent
      when: ansible_connection != 'docker'
  when:
    - ubtu22cis_rule_1_1_1_3
  tags:
    - level1-server
    - level1-workstation
    - automated
    - patch
    - rule_1.1.1.3
    - udf
